name: Python CI with pytest and Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          cd CDA/CDA_FILES
          pip install -r requirements.txt
          pip install --no-cache-dir gpiozero
          apt-get update && apt-get install -y git
          git clone https://github.com/RPi-Distro/RTIMULib.git
          cd RTIMULib/Linux/python && python setup.py install

      - name: Run tests with pytest
        run: pytest ConstrainedDeviceAppTest.py

      - name: Build Docker image
        run: docker build -t my-python-app .

      - name: Run Docker container
        run: docker run my-python-app
